---
- name: Update web servers
  hosts: "{{ target }}"
  remote_user: "{{ remote_user }}"

  vars_prompt:
    - name: remote_user
      prompt: enter the remote host, mostly it will be ubuntu or root
      private: no

    - name: target
      prompt: enter the hostname which you might have mentioned in host file
      private: no

    - name: domain
      prompt: please enter the domain which will be serving the requests(eg sellerapp-staging.datasyndicate.in or ref-seller-app-preprod.ondc.org or ref-seller-app-stage.ondc.org, ref-app-seller-dev-internal.ondc.org, seller-app-preprod-v2.ondc.org )
      private: no

    - name: envtype
      prompt: please enter the env file to copy, we are appending to .env, hence value can be -staging etc
      private: no

  tasks:
    - name: Clone seller-app
      git:
        repo: "https://github.com/ONDC-Official/seller-app.git"
        dest: "/home/ubuntu/seller-app"
        version: "master"
        force: yes

    - name: Clone seller-app-protocol
      git:
        repo: "https://github.com/ONDC-Official/seller-app-protocol.git"
        dest: "/home/ubuntu/seller-app-protocol"
        version: "master"
        force: yes

    - name: Clone seller-app-frontend
      git:
        repo: "https://github.com/ONDC-Official/seller-app-frontend.git"
        dest: "/home/ubuntu/seller-app-frontend"
        version: "master"
        force: yes

    - name: Clone seller-app-igm
      git:
        repo: "https://github.com/ONDC-Official/seller-app-igm.git"
        dest: "/home/ubuntu/seller-app-igm"
        version: "master"
        force: yes

    - name: Clone seller-bugzilla-service
      git:
        repo: "https://github.com/ONDC-Official/seller-bugzilla-service.git"
        dest: "/home/ubuntu/seller-bugzilla-service"
        version: "master"
        force: yes

    - name: Copy lets encrypt with domain replaced
      copy:
        src: "{{ playbook_dir }}/../init-letsencrypt.sh"
        dest: "/home/ubuntu/init-letsencrypt.sh"
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        mode: "0755"

    - name: replace __domain__ with domain name
      replace:
        path: "/home/ubuntu/init-letsencrypt.sh"
        regexp: "__domain_name__"
        replace: "{{ domain }}"


    - name: copy Dockerfile without SSL as dockerfile in seller-app-frontend
      copy:
        src: "{{ playbook_dir }}/../seller-app-frontend/DockerfileWithoutSSL"
        dest: "/home/ubuntu/seller-app-frontend/Dockerfile"
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        mode: "0755"

    - name: replace __domain__ with in nginx.conf
      replace:
        path: "/home/ubuntu/seller-app-frontend/nginx-without-ssl.conf"
        regexp: "__domain_name__"
        replace: "{{ domain }}"

    - name: copy env file with domain replaced
      copy:
        src: "{{ playbook_dir }}/../.env{{ envtype }}"
        dest: "/home/ubuntu/.env"
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        mode: "0755"

    - name: replace __domain__ with domain name
      replace:
        path: "/home/ubuntu/.env"
        regexp: "__domain_name__"
        replace: "{{ domain }}"

    - name: Copy docker compose file with domain replaced
      copy:
        src: "{{ playbook_dir }}/../docker-compose-without-ssl.yaml"
        dest: "/home/ubuntu/docker-compose.yml"
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        mode: "0755"

    #sudo chmod -R a+w ~/.docker-conf/rabbitmq/log

    - name: docker compose up postgres
      shell: "cd /home/ubuntu/ && sudo docker compose up -d postgres"

    - name: docker compose postgres create db, user and password via psql and grant all privileges to schema public
      shell: "cd /home/ubuntu/ && sudo docker compose exec postgres psql -U postgres -c \"CREATE DATABASE  bpp_protocol;\" && sudo docker compose exec postgres psql -U postgres -c \"CREATE USER  bpp_protocol WITH PASSWORD 'bpp_protocol';\" && sudo docker compose exec postgres psql -U postgres -c \"GRANT ALL PRIVILEGES ON DATABASE bpp_protocol TO bpp_protocol;\" && sudo docker compose exec postgres psql -U postgres -c \"GRANT ALL PRIVILEGES ON SCHEMA public TO bpp_protocol;\""
      ignore_errors: yes

    - name: docker compose postgres create db, user and password via psql and grant all privileges to schema public
      shell: "cd /home/ubuntu/ && sudo docker compose exec postgres psql -U postgres -c \"CREATE DATABASE  seller_client;\" && sudo docker compose exec postgres psql -U postgres -c \"CREATE USER  bpp_client WITH PASSWORD 'bpp_client';\" && sudo docker compose exec postgres psql -U postgres -c \"GRANT ALL PRIVILEGES ON DATABASE seller_client TO bpp_client;\" && sudo docker compose exec postgres psql -U postgres -c \"GRANT ALL PRIVILEGES ON SCHEMA public TO bpp_client;\""
      ignore_errors: yes

    - name: Run docker compose up
      shell: "cd /home/ubuntu/ && sudo docker compose build && sudo docker compose up -d"

    - name: run letsencrypt
      shell: "cd /home/ubuntu/ && sudo ./init-letsencrypt.sh"
